language: php
php:
  - '7.3'
  - '7.4'

before_install:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq
  - |
    travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.12.tar.gz | tar xz
    pushd SDL2-2.0.12
    ./configure
    make
    sudo make install
    popd

install:
  - sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev

before_script:
  - composer install
  - pecl install sdl-devel
  - pecl install opengl-devel
  - pecl install openal-devel

script: phpunit tests 
